app = "mc-ai-bot"
primary_region = "nrt"

[build]

[env]
  MC_PORT = "19132"
  MC_USERNAME = "ChatGPT"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpus = 1

[processes]
  app = "node bot.js"
